### ISSUE TITLE
It seems image cannot be built in November 2019

### ISSUE THREAD

**Issue by matks** [ilyaglow/docker-beef#4]
Hi ! I used the latest built image from dockerhub that works very well 👍however it seems it cannot be built anymore, some ruby dependency crashing. Sorry I cant help any further I'm no ruby expert :/

## How to reproduce

Try to build the image, see logs

**Comment by ilyaglow** [comment]
Hi! Thank you for the issue. Sorry that it took so much time to resolve. Should be fixed now.

**Comment by ilyaglow** [comment]
BTW the old version of beef is still available under [ilyaglow/beef:2018-version](https://hub.docker.com/layers/ilyaglow/beef/2018-version/images/sha256-e8c9fb2e4551271cc7be7281c166ca1fc1f72f90785257f75a52e146d28b5d49?context=repo) tag.
